version: '2'
services:
  jenkins-plugins:
    image: rancher/jenkins-plugins:v0.1.1
  jenkins-primary:
    image: jenkins:2.19.4
    entrypoint:
    - /usr/share/jenkins/rancher/jenkins.sh
    volumes_from:
    - jenkins-plugins
    - jenkins-datavolume
    labels:
      io.rancher.scheduler.affinity:host_label: role=01
      io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
      io.rancher.container.hostname_override: container_name
  jenkins-datavolume:
    image: busybox
    entrypoint:
    - chown
    - -R
    - 1000:1000
    - /var/jenkins_home
    volumes:
    - /var/lib/docker/jenkins-ci:/var/jenkins_home
    labels:
      io.rancher.container.start_once: 'true'
  Jenkins-LB:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 28080:28080/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: role=02
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'